<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"图书管理",
			            "menuJump":"列表",
			            "tableName":"tushu"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "修改",
			                "删除"
			            ],
			            "menu":"图书留言管理",
			            "menuJump":"列表",
			            "tableName":"tushuLiuyan"
			        }
			    ],
			    "menu":"图书管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"借阅记录管理",
                        "menuJump":"列表",
                        "tableName":"jieyue"
                    }
                ],
                "menu":"借阅记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyanxinxi"
                    }
                ],
                "menu":"留言管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"出版社管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryChubanshe"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告信息类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"图书类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryTushu"
			        }
			
			    ],
			    "menu":"基础数据管理"
			}
            
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	       {
			    "child":[
			        {
			            "buttons":[
			                "查看",
	                        "借阅"
			            ],
			            "menu":"图书管理",
			            "menuJump":"列表",
			            "tableName":"tushu"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"图书留言管理",
			            "menuJump":"列表",
			            "tableName":"tushuLiuyan"
			        }
			    ],
			    "menu":"图书管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "还书",
	                        "续借"
	                    ],
	                    "menu":"借阅记录管理",
	                    "menuJump":"列表",
	                    "tableName":"jieyue"
	                }
	            ],
	            "menu":"借阅记录管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增"
	                    ],
	                    "menu":"留言管理",
	                    "menuJump":"列表",
	                    "tableName":"liuyanxinxi"
	                }
	            ],
	            "menu":"留言管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
	,
	{
	    "backMenu":[
	       {
			    "child":[
			        {
			            "buttons":[
			                "查看",
	                        "借阅"
			            ],
			            "menu":"图书管理",
			            "menuJump":"列表",
			            "tableName":"tushu"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"图书留言管理",
			            "menuJump":"列表",
			            "tableName":"tushuLiuyan"
			        }
			    ],
			    "menu":"图书管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "还书",
	                        "续借"
	                    ],
	                    "menu":"借阅记录管理",
	                    "menuJump":"列表",
	                    "tableName":"jieyue"
	                }
	            ],
	            "menu":"借阅记录管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增"
	                    ],
	                    "menu":"留言管理",
	                    "menuJump":"列表",
	                    "tableName":"liuyanxinxi"
	                }
	            ],
	            "menu":"留言管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	    ],
	    "frontMenu":[

	    ],
		"roleName":"教师",
		"tableName":"users"
	}
];

var hasMessage = '';
